import type { Metadata } from "next";
import "./globals.css";
import SessionProvider from "@/Session/SessionProvider";
import { Toaster } from "@/components/ui/sonner"

export const metadata: Metadata = {
  title: "Orbit: Your own space",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <SessionProvider>
          {children}
          <Toaster position="top-left" />
        </SessionProvider>
      </body>
    </html>
  );
}
